/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-20 07:44:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import cacao.model.vo.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("cacao.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 String sessionalert = "";

if(session.getAttribute("useremail")!=null){
	sessionalert = String.valueOf(session.getAttribute("useremail"));
};
 String result = "";
 if(session.getAttribute("loginresult")!=null){
		result = String.valueOf(session.getAttribute("loginresult"));
 }; 
 ArrayList<Info> infolist = (ArrayList<Info>)session.getAttribute("cart");
 int cartnum = 0;
 if(infolist==null){
	 cartnum = 0;
 }else{
	 cartnum = infolist.size();
 }
 
 String loginimg = "in";
 int num = 0;

 if(result.equals("")){
	 num = 0;
	 loginimg = "login.png";
 }else{
	 num = 1;
	 loginimg = "logout.jpg";
 }



      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<!-- 헤어css경로 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main/header.css\">\r\n");
      out.write("<!-- 부트스트랩링크 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- 마우스 오버 이벤트 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(document).ready(\r\n");
      out.write("         function() {\r\n");
      out.write("            $(\".dropdown\").hover(\r\n");
      out.write("                  function() {\r\n");
      out.write("                     $('.dropdown-menu', this).not('.in .dropdown-menu')\r\n");
      out.write("                           .stop(true, true).slideDown(\"400\");\r\n");
      out.write("                     $(this).toggleClass('open');\r\n");
      out.write("                  },\r\n");
      out.write("                  function() {\r\n");
      out.write("                     $('.dropdown-menu', this).not('.in .dropdown-menu')\r\n");
      out.write("                           .stop(true, true).slideUp(\"400\");\r\n");
      out.write("                     $(this).toggleClass('open');\r\n");
      out.write("                  });\r\n");
      out.write("         });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\r\n");
      out.write("\tvar icon1 = document.getElementById(\"icon1\");\r\n");
      out.write("\tvar icon2 = document.getElementById(\"icon2\");\r\n");
      out.write("\tvar icon3 = document.getElementById(\"icon3\");\r\n");
      out.write("\tvar icon4 = document.getElementById(\"icon4\");\r\n");
      out.write("\tvar search = document.getElementById(\"search\");\r\n");
      out.write("\r\n");
      out.write("\ticon1.onclick = function(){\r\n");
      out.write("\t\tif(document.getElementById('icon1').alt==0){\r\n");
      out.write("\t\t\twindow.open('/Cacao/Login?cmd=main-page', '로그인폼', 'width=1000px, height=600px');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\tlocation.href=\"/Cacao/Main?cmd=logout-page\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\ticon2.onclick = function(){\r\n");
      out.write("\t\twindow.open(\"/Cacao/YourPage?cmd=main-page\", \"비회원주문조회\", \"width=1000px, height=600px\");\r\n");
      out.write("\t}\r\n");
      out.write("\ticon3.onclick = function(){\r\n");
      out.write("\t\tlocation.href = \"/Cacao/Main?cmd=cartView-page&change=5\";\r\n");
      out.write("\t}\r\n");
      out.write("\ticon4.onclick = function(){\r\n");
      out.write("\t\twindow.open(\"/Cacao/Login?cmd=main-page\", \"로그인폼\", \"width=1000px, height=600px\");\r\n");
      out.write("\t}\r\n");
      out.write("\tsearch.onclick = function(){\r\n");
      out.write("\t\tvar searchtext = document.getElementById(\"searchtext\").value;\r\n");
      out.write("\t\tlocation.href=\"/Cacao/Main?cmd=search-page&searchtext=\"+searchtext;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <header id=\"navigation\" class=\"navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"navbar-header\">\r\n");
      out.write("            <!-- responsive nav button -->\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("               data-target=\".navbar-collapse\">\r\n");
      out.write("               <span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("                  class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                  class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <!-- /responsive nav button -->\r\n");
      out.write("\r\n");
      out.write("            <!-- logo -->\r\n");
      out.write("            <h1 class=\"navbar-brand\"\r\n");
      out.write("               style=\"margin-left: -10em; margin-top: 0.5em\">\r\n");
      out.write("               <a href=\"/Cacao/Main?cmd=main-page\" class=\"link_logo\"> <span\r\n");
      out.write("                  class=\"tit_friends tit_logo\">Team Cacao</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <!-- /logo -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- main nav -->\r\n");
      out.write("         <nav class=\"collapse navigation navbar-collapse navbar-center\"\r\n");
      out.write("            role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <li class=\"dropdown mega-dropdown\"><a\r\n");
      out.write("                  onclick=\"location.href='/Cacao/Product?cmd=pCateView-page'\"\r\n");
      out.write("                  class=\"dropdown-toggle\" data-toggle=\"dropdown\">캐릭터 <span\r\n");
      out.write("                     class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu mega-dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCharLiView-page'\"><img src=\"/Cacao/img/main/라이언.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/무지.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCharApView-page'\"><img src=\"/Cacao/img/main/어피치.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/프로도.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/네오.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/튜브.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/제이지.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-1\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><img src=\"/Cacao/img/main/콘.png\" /></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <li class=\"dropdown mega-dropdown\"><a\r\n");
      out.write("                  onclick=\"location.href='/Cacao/Product?cmd=pCateView-page'\"\r\n");
      out.write("                  class=\"dropdown-toggle\" data-toggle=\"dropdown\">카테고리<span\r\n");
      out.write("                     class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu mega-dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">인형/피규어</li>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCateDollView-page'\"><a>미니인형</a></li>\r\n");
      out.write("                           <li><a href=\"#\">25cm/35cm인형</a></li>\r\n");
      out.write("                           <li><a href=\"#\">대형인형</a></li>\r\n");
      out.write("                           <li><a href=\"#\">키체인인형</a></li>\r\n");
      out.write("                           <li><a href=\"#\">피규어</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">여행/레저</li>\r\n");
      out.write("                           <li><a href=\"#\">여행</a></li>\r\n");
      out.write("                           <li><a href=\"#\">골프</a></li>\r\n");
      out.write("                           <li><a href=\"#\">물놀이</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">리빙</li>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCateCupView-page'\"><a>컵/텀블러</a></li>\r\n");
      out.write("                           <li><a href=\"#\">패브릭</a></li>\r\n");
      out.write("                           <li><a href=\"#\">탈취/방향제</a></li>\r\n");
      out.write("                           <li><a href=\"#\">주방용품</a></li>\r\n");
      out.write("                           <li><a href=\"#\">미용/욕실용품</a></li>\r\n");
      out.write("                           <li><a href=\"#\">생활소품</a></li>\r\n");
      out.write("                           <li><a href=\"#\">푸드</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">생활테크</li>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCatePhoneView-page'\"><a>휴대폰 케이스</a></li>\r\n");
      out.write("                           <li><a href=\"#\">휴대폰 악세서리</a></li>\r\n");
      out.write("                           <li><a href=\"#\">노트북 악세서리</a></li>\r\n");
      out.write("                           <li><a href=\"#\">소형 전자</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">잡화</li>\r\n");
      out.write("                           <li onclick=\"location.href='/Cacao/Product?cmd=pCateShoesView-page'\"><a>신발</a></li>\r\n");
      out.write("                           <li><a href=\"#\">파우치/지갑/가방</a></li>\r\n");
      out.write("                           <li><a href=\"#\">패션소품</a></li>\r\n");
      out.write("                           <li><a href=\"#\">우산</a></li>\r\n");
      out.write("                           <li><a href=\"#\">모자</a></li>\r\n");
      out.write("                           <li><a href=\"#\">교통카드</a></li>\r\n");
      out.write("                           <li><a href=\"#\">시즌소품</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">유아</li>\r\n");
      out.write("                           <li><a href=\"#\">식기</a></li>\r\n");
      out.write("                           <li><a href=\"#\">잡화</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">의류</li>\r\n");
      out.write("                           <li><a href=\"#\">여성의류</a></li>\r\n");
      out.write("                           <li><a href=\"#\">남성의류</a></li>\r\n");
      out.write("                           <li><a href=\"#\">상의</a></li>\r\n");
      out.write("                           <li><a href=\"#\">잠옷</a></li>\r\n");
      out.write("                           <li><a href=\"#\">양말</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">뮤지엄</li>\r\n");
      out.write("                           <li><a href=\"#\">뮤지엄</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">쥬얼리</li>\r\n");
      out.write("                           <li><a href=\"#\">귀걸이</a></li>\r\n");
      out.write("                           <li><a href=\"#\">케이스</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">수비니어</li>\r\n");
      out.write("                           <li><a href=\"#\">수비니어</a></li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"col-sm-2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"dropdown-header\">문구</li>\r\n");
      out.write("                           <li><a href=\"#\">스티커</a></li>\r\n");
      out.write("                           <li><a href=\"#\">필기구</a></li>\r\n");
      out.write("                           <li><a href=\"#\">노트/메모</a></li>\r\n");
      out.write("                           <li><a href=\"#\">카트/엽서</a></li>\r\n");
      out.write("                           <li><a href=\"#\">파일</a></li>\r\n");
      out.write("                           <li><a href=\"#\">데스크 소품</a></li>\r\n");
      out.write("                           <li><a href=\"#\">선물 포장</a></li>\r\n");
      out.write("                           <li class=\"divider\"></li>\r\n");
      out.write("                           <li class=\"dropdown-header\">오마이프렌즈</li>\r\n");
      out.write("                           <li><a href=\"#\">이지웨어</a></li>\r\n");
      out.write("                           <li><a href=\"#\">액티브웨어</a></li>\r\n");
      out.write("                           <li><a href=\"#\">악세서리</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <li class=\"dropdown mega-dropdown\"><a\r\n");
      out.write("                  onclick=\"location.href='/Cacao/MyPage?cmd=main-page'\"\r\n");
      out.write("                  class=\"dropdown-toggle\" data-toggle=\"dropdown\">마이페이지 <span\r\n");
      out.write("                     class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu mega-dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("                     <li class=\"col-sm-3\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><h4>로그인</h4></li>\r\n");
      out.write("                           <li><a href=\"#\"><h4>주문내역</h4></a></li>\r\n");
      out.write("                           <li><a href=\"#\"><h4>찜</h4></a></li>\r\n");
      out.write("                           <li><a href=\"#\"><h4>취소및교환</h4></a></li>\r\n");
      out.write("                           <li><a href=\"#\"><h4>1:1문의</h4></a></li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <li class=\"dropdown mega-dropdown\"><a\r\n");
      out.write("                  onclick=\"location.href='/Cacao/Service?cmd=main-page'\"\r\n");
      out.write("                  class=\"dropdown-toggle\" data-toggle=\"dropdown\">고객센터<span\r\n");
      out.write("                     class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu mega-dropdown-menu\">\r\n");
      out.write("                     <li class=\"col-sm-3\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><h4>공지사항</h4></li>\r\n");
      out.write("                           <li><a href=\"#\"><h4>FAQ</h4></a></li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("               <li><a href=\"#\">매장안내</a></li>\r\n");
      out.write("               <li><a href=\"#\">뮤지엄</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("               <li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"input-group stylish-input-group\"\r\n");
      out.write("                     style=\"width: 10em; margin-top: 15%\">\r\n");
      out.write("                     <input type=\"text\" id='searchtext' class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                     <span class=\"input-group-addon\">\r\n");
      out.write("                        <button id = 'search' type=\"button\">\r\n");
      out.write("                           <span class=\"glyphicon glyphicon-search\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                     </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <!-- 로그인 버튼 -->\r\n");
      out.write("\r\n");
      out.write("               <li><img id='icon1' style=\"width:30px;height:30px;margin-top:25px;margin-left:30px\" alt='");
      out.print(num);
      out.write("' src=\"/Cacao/img/main/");
      out.print(loginimg );
      out.write("\" /></li>\r\n");
      out.write("               <li><img id='icon2'style=\"width:30px;height:30px;margin-top:25px;margin-left:30px\" src=\"/Cacao/img/main/non.png\"/></li>\r\n");
      out.write("               <li><img id='icon3'style=\"width:30px;height:30px;margin-top:25px;margin-left:30px\" src=\"/Cacao/img/main/cart/cart");
      out.print(cartnum );
      out.write(".png\"/></li>\r\n");
      out.write("               <li><img id='icon4'style=\"width:30px;height:30px;margin-top:25px;margin-left:30px\" src=\"/Cacao/img/main/foreign.png\"/></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </nav>\r\n");
      out.write("\r\n");
      out.write("         <!-- /main nav -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--\r\n");
      out.write("        End Fixed Navigation\r\n");
      out.write("        ==================================== -->\r\n");
      out.write("   <!-- main jQuery -->\r\n");
      out.write("   <script src=\"/Cacao/js/vendor/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("   <!-- Bootstrap -->\r\n");
      out.write("   <script src=\"/Cacao/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <!-- jquery.nav -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery.nav.js\"></script>\r\n");
      out.write("   <!-- Portfolio Filtering -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("   <!-- Fancybox -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("   <!-- Parallax sections -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery.parallax-1.1.3.js\"></script>\r\n");
      out.write("   <!-- jQuery Appear -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery.appear.js\"></script>\r\n");
      out.write("   <!-- countTo -->\r\n");
      out.write("   <script src=\"/Cacao/js/jquery-countTo.js\"></script>\r\n");
      out.write("   <!-- owl carousel -->\r\n");
      out.write("   <script src=\"/Cacao/js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <!-- WOW script -->\r\n");
      out.write("   <script src=\"/Cacao/js/wow.min.js\"></script>\r\n");
      out.write("   <!-- theme custom scripts -->\r\n");
      out.write("   <script src=\"/Cacao/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
