/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-11-04 08:49:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");

   String pjName = "/Cacao";

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Cacao LoginForm</title>\r\n");
      out.write("<!-- 로그인CSS  -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/login/loginForm.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#loginBtn').click(function(){\r\n");
      out.write("\t\tif($('#user').val()==\"\"){\r\n");
      out.write("\t   \t\talert('아이디를 입력하세요');\t\t\t\r\n");
      out.write("\t\t}else if($('#pass').val()==\"\"){\r\n");
      out.write("\t\t\talert('패스워드를 입력하세요');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("\t\t\t$('#loginFrm').submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\n");
      out.write("\n");
      out.write("=======\n");
      out.write("\t\t\t$('#loginFrm').submit();\n");
      out.write("\t\t}\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\t});\n");
      out.write("<<<<<<< HEAD\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\r\n");
      out.write("=======\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\n");
      out.write("\t$('#findEmail').click(function(){\r\n");
      out.write("\t\twindow.open(\"");
      out.print(pjName );
      out.write("/Login?cmd=loginEmailFind-page\", \"이메일찾기\",\r\n");
      out.write("\t\t\"width=550px, height=600px\");\r\n");
      out.write("\t});\r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("=======\n");
      out.write("\r\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\n");
      out.write("<<<<<<< HEAD\n");
      out.write("\n");
      out.write("\n");
      out.write("=======\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\t$('#findPwd').click(function(){\r\n");
      out.write("\t\twindow.open(\"");
      out.print(pjName );
      out.write("/Login?cmd=loginPwdFind-page\", \"비밀번호찾기\",\r\n");
      out.write("\t\t\"width=550px, height=600px\");\r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("\t});\r\n");
      out.write("=======\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\n");
      out.write("<<<<<<< HEAD\n");
      out.write("\n");
      out.write("\n");
      out.write("=======\n");
      out.write("\t});\n");
      out.write(">>>>>>> branch 'master' of https://github.com/seungyang/Cacao\n");
      out.write("\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\t<div style='width: 100%; height: 5px;'></div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t전체바디 div시작 -->\r\n");
      out.write("\t<div style=\"background-color: #FFF203;\">\r\n");
      out.write("<!-- \t헤더 -->\r\n");
      out.write("\t\t<header style=\"margin-top: 2%; background-color: white;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<font\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 15; font-weight: bold; margin-left: 2%; color: grey\">Cacao\r\n");
      out.write("\t\t\t\t\t로그인</font><img src=\"/Cacao/img/login/loginheader.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 20px; margin-left: 74%;\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t</header>\r\n");
      out.write("<!-- 바디\t\t -->\r\n");
      out.write("\t\t<div class=\"loginmodal-container\"\r\n");
      out.write("\t\t\tstyle=\"background-color: white; width: 28%; height: 380px;\">\r\n");
      out.write("\t\t\t<h1 style=\"text-align: left; margin-top: -12px; color: #5a5a5a;\">Cacao</h1>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form style=\"margin-top: -20px\"id='loginFrm' class=\"form-login\" name='loginFrm' action=\"");
      out.print(pjName );
      out.write("/Login?cmd=login-page\" method='post'>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id= \"user\" name=\"user\" placeholder=\"카카오계정 (이메일)\" style=\"height: 15%;\"> \r\n");
      out.write("\t\t\t\t<input type=\"password\" id= \"pass\" name=\"pass\" placeholder=\"비밀번호(4~16자리)\" style=\"height: 15%;\"> \r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"login\" class=\"button button5\" id=\"loginBtn\" value=\"로그인\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 20px; font-weight: bold;\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"margin-top: 97.5px;\">\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(pjName );
      out.write("/Register?cmd=joinAgree-page\"><font style=\"font-size: 10; color: black;\">회원가입</font></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"findEmail\"><fon-t style=\"font-size: 10; margin-left: 86px; color: black;\">이메일\r\n");
      out.write("\t\t\t\t\t\t찾기</font></a> - <a href=\"#\" id=\"findPwd\"><font style=\"font-size:10;color: black;\">비밀번호 재설정</font></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- 푸터 -->\r\n");
      out.write("\t\t<footer style=\"background-color: white;\">\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img src=\"/Cacao/img/login/loginfoot.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 55px; margin-left: 23%;\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
