/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-19 09:44:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinInfoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- CSS  ============================================= -->\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Animate -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/animate.css\">\r\n");
      out.write("<!-- Main Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("<title>회원가입 정보입력</title>\r\n");
      out.write("<!-- ###################joinInfoForm CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/register/joinInfoForm.css\">\r\n");
      out.write("\r\n");

	String pjName = "/Cacao";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//################ 입력정보 유효성 검사\r\n");
      out.write("\tfunction checkfield() {\r\n");
      out.write("\t\tvar exptext = /^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/;\r\n");
      out.write("\r\n");
      out.write("\t\tif (document.signup.emailid.value == \"\") {\r\n");
      out.write("\t\t\talert(\"이메일을 입력하세요\");\r\n");
      out.write("\t\t\tdocument.signup.emailid.focus();\r\n");
      out.write("\t\t} else if (document.signup.password.value == \"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\tdocument.signup.password.focus();\r\n");
      out.write("\t\t} else if (document.signup.cpassword.value == \"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호확인을 입력하세요\");\r\n");
      out.write("\t\t\tdocument.signup.cpassword.focus();\r\n");
      out.write("\t\t} else if (document.signup.mem_name.value == \"\") {\r\n");
      out.write("\t\t\talert(\"닉네임을 입력하세요\");\r\n");
      out.write("\t\t\tdocument.signup.mem_name.focus();\r\n");
      out.write("\t\t} else if (document.signup.password.value != document.signup.cpassword.value) {\r\n");
      out.write("\t\t\t//비밀번호와 비밀번호확인의 값이 다를 경우\r\n");
      out.write("\t\t\talert(\"입력한 2개의 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\tdocument.signup.password.focus();\r\n");
      out.write("\t\t} else if (exptext.test(document.signup.emailid.value) == false) {\r\n");
      out.write("\t\t\t//이메일 형식이 알파벳+숫자@알파벳+숫자.알파벳+숫자 형식이 아닐경우\r\n");
      out.write("\t\t\talert(\"이 메일형식이 올바르지 않습니다.\");\r\n");
      out.write("\t\t\tdocument.signup.emailid.focus();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.signup.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ####상단노란테두리 -->\r\n");
      out.write("\t<div style='background: yellow; width: 100%; height: 5px;'></div>\r\n");
      out.write("<!-- #### 전체 div 시작 -->\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<header style=\"margin-top: 2%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<font\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 22; font-weight: bold; margin-left: 2%; color: grey\">Cacao\r\n");
      out.write("\t\t\t\t\t계정만들기</font><img src=\"../../img/login/loginheader.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 20px; margin-left: 70%;\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div style=\"margin-top: -2%;\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"../../img/register/agreeBtnImg2.png\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: 10%; height: 60px; margin-top: -0.24%;\"> <img\r\n");
      out.write("\t\t\t\talt=\"\" src=\"../../img/register/agreeInput2.png\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: -1%; height: 60px;\"\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\tsrc=\"../../img/register/agreeInput3.png\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: -1%; height: 60px;\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8\" style=\"margin-left: 15%\">\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("<!-- \t\t\t\t\tFORM 시작 -->\t\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\"\r\n");
      out.write("\t\t\t\t\taction=\"");
      out.print(pjName);
      out.write("/Register?cmd=joinInfoSave-page\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tname=\"signup\" id=\"signup\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">카카오계정 이메일 <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"emailid\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"emailid\" placeholder=\"이메일은 아이디로 사용됩니다\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 220%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label label-danger\" style=\"margin-left: 29%\">Note:-</span><br>\r\n");
      out.write("\t\t\t\t\t\t<small style=\"margin-left: 29%\">· 입력한 이메일로 가입인증번호가 발송됩니다.</small><br>\r\n");
      out.write("\t\t\t\t\t\t<small style=\"margin-left: 29%\">· 꼭 실제로 사용중인 이메일주소를\r\n");
      out.write("\t\t\t\t\t\t\t입력해주세요. </small><br> <small style=\"margin-left: 29%\">· 비밀번호\r\n");
      out.write("\t\t\t\t\t\t\t분실 시 이메일을 통해 재설정이 가능합니다.</small>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">비밀번호 <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"password\" placeholder=\"비밀번호 (8~16자리)\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 220%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">비밀번호 재입력 <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"cpassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"cpassword\" placeholder=\"비밀번호 재입력\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 220%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<small style=\"margin-left: 29%\">· 비밀번호는 8~16자의 영문 대소문자,\r\n");
      out.write("\t\t\t\t\t\t\t숫자, 특수문자를 조합하여 설정해주세요.</small><br> <small style=\"margin-left: 29%\">·\r\n");
      out.write("\t\t\t\t\t\t\t다른사이트에서 사용하는 것과 동일하거나 쉬운 비밀번호는 사용하지 마세요. </small><br> <small\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-left: 29%\">· 안전한 계정 사용을 위해 비밀번호는 주기적으로\r\n");
      out.write("\t\t\t\t\t\t\t변경해주세요.</small>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">닉네임<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mem_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"mem_name\" placeholder=\"닉네임을 설정해주세요\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 88%; margin-left: -4%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t#################\tBIRTH : 날짜 선택 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">생년월일 <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-inline\" style=\"margin-left: -4%\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t####### 년도 : YYYY선택 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"yyyy\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0\">연도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (int i = 1955; i < 2011; i++) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t#######\t월 : MM선택 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"mm\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">월</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for(int j=1; j<=12; j++){
												if(j/10==0)	{	
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(0+""+j);
      out.write('"');
      out.write('>');
      out.print(0+""+j);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t####### 일 : DD선택 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"dd\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");


											for(int j=1; j<=31; j++){
												if(j/10==0)	{
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(0+""+j);
      out.write('"');
      out.write('>');
      out.print(0+""+j);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("<!-- \t\t\t\t\tBIRTH : 날짜 선택 END -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t####### GENDER : 성별 선택 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 7%;\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-3\">Gender <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t<label> <input name=\"gender\" type=\"radio\" value=\"남성\"\r\n");
      out.write("\t\t\t\t\t\t\t\tchecked> 남성\r\n");
      out.write("\t\t\t\t\t\t\t</label>     <label> <input name=\"gender\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"여성\"> 여성\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<!-- \t\t\t\t\tGENDER : 성별 선택 END-->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t####### 다음버튼 : joinInfoSave통해서 DB저장되고, 화면은 joinAuth페이지로 이동 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 45%; margin-top: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"Submit\" type=\"button\" value=\"다음 \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\" style=\"width: 30%; height: 50px;\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"checkfield()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<!-- \t\t\t\t\t다음버튼 END -->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("<!-- \t\t\t\t\tFORM END -->\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- #### 전체 div 끝 -->\t\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<img src=\"../../img/login/loginfoot.png\"\r\n");
      out.write("\t\t\t\tstyle=\"height: 55px; margin-left: 23%;\" />\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
