/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-20 07:26:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import cacao.model.vo.*;

public final class adminServiceMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("cacao.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
List<Service> serviceList = (List) request.getAttribute("serviceResult"); 
      out.write('\r');
      out.write('\n');

   String pjName = "/Cacao"; 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title> What to do </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body ng-app=\"myApp\" ng-controller=\"userCtrl\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:100%\">\r\n");
      out.write("<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/admin/adminservice.png\" style=\"width: 100%; height: 240px\">\r\n");
      out.write("\r\n");
      out.write("<div display=\"inline\" style=\"width:60%; float:left; margin-left: 30px;\">\r\n");
      out.write("<h2><a class=\"w3-btn w3-green w3-ripple\" href=\"/Cacao/Admin?cmd=main-page\">뒤로가기</a></h2>\r\n");
      out.write("\r\n");
      out.write("<table class=\"w3-table w3-bordered w3-striped\">\r\n");
      out.write("  <tr>\r\n");
      out.write("  \t<th></th>\r\n");
      out.write("    <th>유형</th>\r\n");
      out.write("    <th>카테고리</th>\r\n");
      out.write("    <th>제목</th>\r\n");
      out.write("    <th>내용</th>\r\n");
      out.write("    <th>첨부파일</th>\r\n");
      out.write("    <th>수정</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("  <tr ng-repeat=\"user in users\">\r\n");
      out.write("  \t<td style=\"visibility: hidden;\">{{user.number}}</td>\r\n");
      out.write("    <td>{{user.kind}}</td>\r\n");
      out.write("    <td>{{user.cate}}</td>\r\n");
      out.write("    <td>{{user.title}}</td>\r\n");
      out.write("    <td>{{user.detail}}</td>\r\n");
      out.write("    <td>{{user.image}}</td>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <td>\r\n");
      out.write("      <button class=\"w3-btn w3-ripple\" ng-click=\"editUser(user.id)\">✎ Edit</button>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:30%; float:left; margin-left:30px; margin-top:20px;\">\r\n");
      out.write("<button class=\"w3-btn w3-green w3-ripple\" ng-click=\"editUser('new')\">✎ Create New User</button>\r\n");
      out.write("\r\n");
      out.write("<form ng-hide=\"hideform\" id='serviceInsert' name='serviceInsert' action=\"");
      out.print(pjName );
      out.write("/Admin?cmd=adminServiceSave-page\" method='post'>\r\n");
      out.write("  <h3 ng-show=\"edit\">등록</h3>\r\n");
      out.write("  <h3 ng-hide=\"edit\">수정</h3>\r\n");
      out.write("    <label>유형</label>\r\n");
      out.write("    <select id=\"qCate\" name=\"servicekind\" class=\"w3-input w3-border\" ng-model=\"kind\">\r\n");
      out.write("     \t\t <option value=\"0\">문의 유형을 선택하세요</option>\r\n");
      out.write("     \t\t <option value=\"FAQ\">FAQ</option>\r\n");
      out.write("     \t\t <option value=\"공지사항\">공지사항</option>\r\n");
      out.write("   \t</select>\r\n");
      out.write("  <br>\r\n");
      out.write("    <label>카테고리</label>\r\n");
      out.write("    <input class=\"w3-input w3-border\" type=\"text\" name = \"servicecate\" ng-model=\"cate\" placeholder=\"카테고리를 입력하세요\">\r\n");
      out.write("  <br>\r\n");
      out.write("    <label>제목</label>\r\n");
      out.write("    <input class=\"w3-input w3-border\" type=\"text\" name = \"servicetitle\" ng-model=\"title\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("  <br>\r\n");
      out.write("    <label>내용</label>\r\n");
      out.write("    <textarea class=\"w3-input w3-border\" ng-model=\"detail\" name=\"servicedetail\" rows=\"7\" cols=\"24\" placeholder=\"내용을 입력하세요\" ></textarea>\r\n");
      out.write("  <br>\r\n");
      out.write("   <br>\r\n");
      out.write("    <label>첨부파일</label>\r\n");
      out.write("    <input class=\"w3-input w3-border\" ng-model=\"image\" id=\"file\" name=\"serviceimage\" type=\"file\" placeholder=\"첨부 파일공간\" >\r\n");
      out.write("  <br>\r\n");
      out.write("  <input type=\"submit\" class=\"w3-btn w3-green w3-ripple\" ng-disabled=\"error || incomplete\" value=\"✔ Save Changes\">\r\n");
      out.write("    <input style=\"visibility: hidden;\"class=\"w3-input w3-border\" ng-model=\"number\" id=\"serviceid\" name=\"serviceid\" type=\"text\">\r\n");
      out.write("  \r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("angular.module('myApp', []).controller('userCtrl', function($scope) {\r\n");
      out.write("$scope.number = '';\r\n");
      out.write("$scope.kind = '';\r\n");
      out.write("$scope.cate = '';\r\n");
      out.write("$scope.title = '';\r\n");
      out.write("$scope.detail = '';\r\n");
      out.write("$scope.image = '';\r\n");
      out.write("$scope.users = [\r\n");
      out.write("\r\n");
for(int i=0; i< serviceList.size(); i++){ 
      out.write("\r\n");
      out.write("\t{id:");
      out.print(i+1);
      out.write(", number:'");
      out.print(serviceList.get(i).getsId());
      out.write("', kind:'");
      out.print(serviceList.get(i).getsKind());
      out.write("', cate: \"");
      out.print(serviceList.get(i).getsCate());
      out.write("\", title: \"");
      out.print(serviceList.get(i).getsTitle());
      out.write("\", detail: \"");
      out.print(serviceList.get(i).getsDetail());
      out.write("\", image: \"");
      out.print(serviceList.get(i).getsImage());
      out.write("\"},\r\n");
}
      out.write("\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("//alert($scope.users.length);\r\n");
      out.write("\r\n");
      out.write("$scope.edit = true;\r\n");
      out.write("$scope.error = false;\r\n");
      out.write("$scope.incomplete = false; \r\n");
      out.write("$scope.hideform = true; \r\n");
      out.write("$scope.editUser = function(id) {\r\n");
      out.write("  $scope.hideform = false;\r\n");
      out.write("  if (id == 'new') {\r\n");
      out.write("    $scope.edit = true;\r\n");
      out.write("    $scope.incomplete = true;\r\n");
      out.write("    $scope.number = 0;\r\n");
      out.write("    $scope.kind = '';\r\n");
      out.write("    $scope.cate = '';\r\n");
      out.write("    $scope.title = '';\r\n");
      out.write("    $scope.detail = '';\r\n");
      out.write("    $scope.image = '';\r\n");
      out.write("    } else {\r\n");
      out.write("   $scope.edit = false;\r\n");
      out.write("   $scope.number = $scope.users[id-1].number;\r\n");
      out.write("   $scope.kind = $scope.users[id-1].kind;\r\n");
      out.write("   $scope.cate = $scope.users[id-1].cate;\r\n");
      out.write("   $scope.title = $scope.users[id-1].title;\r\n");
      out.write("   $scope.detail = $scope.users[id-1].detail;\r\n");
      out.write("   $scope.image = $scope.users[id-1].image;\r\n");
      out.write("  }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$scope.$watch('number',function(){$scope.test();});\r\n");
      out.write("$scope.$watch('kind', function() {$scope.test();});\r\n");
      out.write("$scope.$watch('cate', function() {$scope.test();});\r\n");
      out.write("$scope.$watch('title',function() {$scope.test();});\r\n");
      out.write("$scope.$watch('detail',function() {$scope.test();});\r\n");
      out.write("$scope.$watch('image',function() {$scope.test();});\r\n");
      out.write("\r\n");
      out.write("$scope.test = function() {\r\n");
      out.write("\t\r\n");
      out.write("  if ($scope.edit && (!$scope.kind.length || !$scope.cate.length || !$scope.title.length || !$scope.detail.length || !$scope.image.length)) {\r\n");
      out.write("     $scope.incomplete = true;\r\n");
      out.write("  }\r\n");
      out.write("  $scope.incomplete = false;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("});    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
