/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-20 07:25:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 String pjName = "/Cacao"; 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title> 카카오프렌즈 관리자페이지 </title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html {\r\n");
      out.write("    font-family: Lato, 'Helvetica Neue', Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h5 {\r\n");
      out.write("    font-size: 1.28571429em;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 1.2857em;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: .28571429rem;\r\n");
      out.write("    box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-block {\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 1em;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-top: 1px solid rgba(34, 36, 38, .1);\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-img-top {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title {\r\n");
      out.write("    font-size: 1.28571429em;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 1.2857em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-text {\r\n");
      out.write("    clear: both;\r\n");
      out.write("    margin-top: .5em;\r\n");
      out.write("    color: rgba(0, 0, 0, .68);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    position: static;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    padding: .75em 1em;\r\n");
      out.write("    color: rgba(0, 0, 0, .4);\r\n");
      out.write("    border-top: 1px solid rgba(0, 0, 0, .05) !important;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-inverse .btn {\r\n");
      out.write("    border: 1px solid rgba(0, 0, 0, .05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -12px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    width: 25px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    border: 1px solid #fff;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-avatar {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-inline {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-inline ~ .card-title {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-left: 4px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-bold {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".meta {\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    color: rgba(0, 0, 0, .4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".meta a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: rgba(0, 0, 0, .4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".meta a:hover {\r\n");
      out.write("    color: rgba(0, 0, 0, .87);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#product').click(function(){\r\n");
      out.write("\t\t\tvar result = confirm('상품관리 페이지로 이동하시겠습니까?'); \r\n");
      out.write("\t\t\t \tif(result) { \r\n");
      out.write("\t\t\t \t\tlocation.replace('");
      out.print(pjName);
      out.write("/Admin?cmd=adminProductMain-page'); \r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#orderlist').click(function(){\r\n");
      out.write("\t\t\tvar result = confirm('주문관리 페이지로 이동하시겠습니까?'); \r\n");
      out.write("\t\t\t \tif(result) { \r\n");
      out.write("\t\t\t \t\tlocation.replace('");
      out.print(pjName);
      out.write("/Admin?cmd=adminOrderMain-page'); \r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#mypage').click(function(){\r\n");
      out.write("\t\t\tvar result = confirm('문의관리 페이지로 이동하시겠습니까?'); \r\n");
      out.write("\t\t\t \tif(result) { \r\n");
      out.write("\t\t\t \t\tlocation.replace('");
      out.print(pjName);
      out.write("/Admin?cmd=adminMyPageMain-page'); \r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#service').click(function(){\r\n");
      out.write("\t\t\tvar result = confirm('고객센터관리 페이지로 이동하시겠습니까?'); \r\n");
      out.write("\t\t\t \tif(result) { \r\n");
      out.write("\t\t\t \t\tlocation.replace('");
      out.print(pjName);
      out.write("/Admin?cmd=adminServiceMain-page'); \r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \t<div class='header'>\r\n");
      out.write("\t\t<img src=\"https://t1.daumcdn.net/friends/prod/category/W001_friends_ryan1.jpg\" class=\"img_intro rw_show\" alt=\"라이언\">\r\n");
      out.write("\t\t<img src=\"https://t1.daumcdn.net/friends/prod/category/M001_friends_ryan2.jpg\" class=\"img_intro rw_hide\" alt=\"라이언\">\r\n");
      out.write("\t\t\t<h2 id=\"kakaoBody\" class=\"tit_intro\">라이언</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 10%;\">\r\n");
      out.write("        <h1 style=\"text-align: center; margin-bottom: 20px;\">관리자 페이지</h1>\r\n");
      out.write("            <!-- 상품 관리자 페이지  --> \r\n");
      out.write("            <div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("                <div class=\"card card-inverse card-info\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"/Cacao/img/admin/lion.png\">\r\n");
      out.write("                    <div class=\"card-block\">\r\n");
      out.write("                        <h4 class=\"card-title\">상품 관리</h4>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          \t  상품 정보관리 및 재고관리\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("                        <button class=\"btn btn-info btn-sm\" id=\"product\">상품</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 주문 관리자 페이지  --> \r\n");
      out.write("            <div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("                <div class=\"card card-inverse card-info\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"/Cacao/img/admin/muzi.png\">\r\n");
      out.write("                    <div class=\"card-block\">\r\n");
      out.write("                        <h4 class=\"card-title\">주문 관리</h4>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          \t  주문상태변경 및 취소관리\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("                        <button class=\"btn btn-info btn-sm\" id=\"orderlist\">주문</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 1:1문의 관리자 페이지  --> \r\n");
      out.write("            <div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("                <div class=\"card card-inverse card-info\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"/Cacao/img/admin/neo.png\">\r\n");
      out.write("                    <div class=\"card-block\">\r\n");
      out.write("                        <h4 class=\"card-title\">문의 관리</h4>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          \t  마이페이지 내 1:1 문의 관리\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("                        <button class=\"btn btn-info btn-sm\" id=\"mypage\">문의</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 고객센터 관리자 페이지  --> \r\n");
      out.write("            <div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("                <div class=\"card card-inverse card-info\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"/Cacao/img/admin/jayz.png\">\r\n");
      out.write("                    <div class=\"card-block\">\r\n");
      out.write("                        <h4 class=\"card-title\">고객센터 관리</h4>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          \t  공지사항 및 FAQ 관리\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("                        <button class=\"btn btn-info btn-sm\" id=\"service\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
