/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-18 15:26:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPageQAForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

   String pjName = "/Cacao";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(pjName );
      out.write("/css/mypage/qabtn.css\" />\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("   $('#qaCencel').click(function(){\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      window.location = '/Cacao/MyPage?cmd=main-page&page=4';\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $('#qaSubmit').click(function () {\r\n");
      out.write("\t\tif($('#qCate').val()==0){\r\n");
      out.write("\t   \t\talert('유형을 선택하세요');\t\t\t\r\n");
      out.write("\t\t}else if($('#qTitle').val()==\"\"){\r\n");
      out.write("\t\t\talert('제목을 입력하세요');\r\n");
      out.write("\t\t}else if($('#qContent').val()==\"\"){\r\n");
      out.write("\t\t\talert('내용을 입력하세요');\r\n");
      out.write("\t\t}else{\r\n");
      out.write(" \t\t\t$('#qaFrm').submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*  */\r\n");
      out.write("   });\r\n");
      out.write("});   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title> 우리반 연습</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form class=\"form-horizontal\" id='qaFrm' name='qaFrm' action=\"");
      out.print(pjName );
      out.write("/MyPage?cmd=myPageQASave-page\" method='post'>\r\n");
      out.write("<legend style=\"text-align: center\">문의 내용</legend>\r\n");
      out.write("<!-- Select Basic -->\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("  <label class=\"col-md-4 control-label\" for=\"qCate\">유형</label>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <select id=\"qCate\" name=\"qCate\" class=\"form-control\">\r\n");
      out.write("      <option value=\"0\">문의 유형을 선택하세요</option>\r\n");
      out.write("      <option value=\"회원\">회원</option>\r\n");
      out.write("      <option value=\"상품\">상품</option>\r\n");
      out.write("      <option value=\"주문결제\">주문결제</option>\r\n");
      out.write("      <option value=\"배송\">배송</option>\r\n");
      out.write("      <option value=\"쿠폰\">쿠폰</option>\r\n");
      out.write("      <option value=\"교환/반품/환불\">교환/반품/환불</option>\r\n");
      out.write("      <option value=\"기타\">기타</option>\r\n");
      out.write("      <option value=\"해외배송\">해외배송</option>\r\n");
      out.write("   </select>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("  <label class=\"col-md-4 control-label\" for=\"qTitle\">제목</label>  \r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("  <input id=\"qTitle\" name=\"qTitle\" type=\"text\" class=\"form-control input-md\" required=\"\">\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("  <label class=\"col-md-4 control-label\" for=\"qContent\">내용</label>  \r\n");
      out.write("  <div class=\"col-md-5\">\r\n");
      out.write("  <textarea  id=\"qContent\" class=\"form-control input-md\" name=\"qContent\" rows=\"10\" cols=\"20\"></textarea>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("  <label class=\"col-md-4 control-label\" for=\"qFile\">첨부 파일</label>  \r\n");
      out.write("  <div class=\"col-md-5\">\r\n");
      out.write("  <input id=\"qFile\" name=\"qFile\" type=\"text\" placeholder=\"첨부 파일공간\" class=\"form-control input-md\">\r\n");
      out.write("  <span class=\"help-block\">\r\n");
      out.write("  * 상품 불량 및 오배송의 경우, 해당 제품 사진을 등록 부탁드립니다.<br/>\r\n");
      out.write("  * 첨부파일은 1개만 등록 가능하며, 최대 10M의 용량 제한이 있습니다.<br/>\r\n");
      out.write("  * 첨부 파일은 1개만 등록가능합니다.<br/>\r\n");
      out.write("  </span>  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"btn_wrap\">\r\n");
      out.write("   <div class=\"col three\">            \r\n");
      out.write("      <a href=\"#\" class=\"btn2 btn-sunflower2\" id=\"qaCencel\">취소하기</a>         \r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col three\">            \r\n");
      out.write("      <a href=\"#\" class=\"btn btn-sunflower\" id=\"qaSubmit\">등록하기</a>         \r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
