/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-20 07:44:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cacaoMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    response.setHeader("P3P","CP='CAO PSA CONi OTR OUR DEM ONL'"); 
	
	String loginId = null;
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie cookie : cookies) {
			if (cookie.getName().equalsIgnoreCase("loginId")) {
				loginId = cookie.getValue();
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"one page, business template, single page, onepage, responsive, parallax, creative, business, html5, css3, css3 animation\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>카카오프렌즈</title>\r\n");
      out.write("<link href=\"/Cacao/css/header.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"/Cacao/js/vendor/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("        End Fixed Navigation\r\n");
      out.write("        ==================================== -->\r\n");
      out.write("\t<!--\r\n");
      out.write("        Home Slider\r\n");
      out.write("        ==================================== -->\r\n");
      out.write("\t<section id=\"home\">\r\n");
      out.write("\t\t<div id=\"home-carousel\" class=\"carousel slide\" data-interval=\"false\">\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<li data-target=\"#home-carousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#home-carousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#home-carousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<!--/.carousel-indicators-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item active\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url('https://t1.daumcdn.net/friends/prod/banner/20170901_ribbonryan_Rbanner_W.gif');\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url('https://t1.daumcdn.net/friends/prod/banner/20171010_Rbanner_bodypillow_W.jpg');\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url('https://t1.daumcdn.net/friends/prod/banner/20170907_minicushion_Rbanner_W.jpg');\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.carousel-inner-->\r\n");
      out.write("\t\t\t<nav id=\"nav-arrows\"\r\n");
      out.write("\t\t\t\tclass=\"nav-arrows hidden-xs hidden-sm visible-md visible-lg\">\r\n");
      out.write("\t\t\t\t<a class=\"sl-prev hidden-xs\" href=\"#home-carousel\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-angle-left fa-3x\"></i>\r\n");
      out.write("\t\t\t\t</a> <a class=\"sl-next\" href=\"#home-carousel\" data-slide=\"next\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-angle-right fa-3x\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"background\" style=\"height: 4200px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"portfolio\" style=\"margin-top: 10%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">Team Cacao 추천상품</h2>\r\n");
      out.write("\t\t\t\t<!--         <hr class=\"star-primary\"> -->\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 3.5%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/caseMain.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 320px; width: 320px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/bottleMain.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 320px; width: 320px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/garbageMain.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 320px; width: 320px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/dollMain.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 320px; width: 320px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 320px; width: 666.5px; margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/noteMain.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 320px; width: 660px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- \t//새로나온 신상품-->\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"portfolio\" style=\"margin-top: 10%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">새로나온신상품</h2>\r\n");
      out.write("\t\t\t\t<!--         <hr class=\"star-primary\"> -->\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 3.5%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char3.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char4.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char5.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char6.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char7.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char8.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/char9.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- \t//캐릭터 상품 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"portfolio\" style=\"margin-top: 9%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">캐릭터별 상품 보러가기</h2>\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 3.5%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_muzi.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_neo.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_ryan.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_tube.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/i_apeach.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_con.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_frodo.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-link\" href=\"#portfolioModal1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/ico_jayg.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 120px; width: 105%;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!--        배너광고 -->\r\n");
      out.write("\t\t<section style=\"margin-top: 9%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">배너광고</h2>\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/cacao/bannerCacao2.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\" style=\"height: 220px; width: 101%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- \t//인기상품-->\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"portfolio\" style=\"margin-top: 7%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">인기상품</h2>\r\n");
      out.write("\t\t\t\t<!--         <hr class=\"star-primary\"> -->\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 3.5%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언2.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언3.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언4.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/어피치1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언5.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/어피치2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언6.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"\" href=\"\"> <img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/favorite/라이언7.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" style=\"height: 240px; width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"fa fa-search-plus fa-3x\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/portfolio/cart.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px;\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 팀소개 링크 이미지-->\r\n");
      out.write("\t\t<section style=\"margin-top: 9%\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-left\" style=\"color: black;\">우리 개발자를 소개합니다</h2>\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/aboutTeamImg.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\" style=\"height: 200px; width: 101%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
