/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-20 08:16:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import cacao.model.vo.*;

public final class pCateCaseView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("cacao.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
int cnt = Integer.parseInt(request.getParameter("cnt"));
String id = request.getParameter("id");
String detail = request.getParameter("detail");
String name =  request.getParameter("name");
String price = request.getParameter("price");
List<Info> infolist = new <Info>ArrayList();
Info info = new Info();
info.setiId(id);
info.setiDetail(detail);
info.setiName(name);
info.setiCost(price);
infolist.add(info);
session.setAttribute("buylist", infolist);
String imgstr = "";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"one page, business template, single page, onepage, responsive, parallax, creative, business, html5, css3, css3 animation\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>카카오프렌즈</title>\r\n");
      out.write(" \r\n");
      out.write("<!--\r\n");
      out.write("        Google Fonts\r\n");
      out.write("        ============================================= -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("        CSS\r\n");
      out.write("        ============================================= -->\r\n");
      out.write("<!-- Fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Fancybox -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/jquery.fancybox.css\">\r\n");
      out.write("<!-- owl carousel -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/owl.carousel.css\">\r\n");
      out.write("<!-- Animate -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/animate.css\">\r\n");
      out.write("<!-- Main Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/main.css\">\r\n");
      out.write("<!-- Main Responsive -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/Cacao/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- product페이지 css -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizer Script for old Browsers -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 스타일시도 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#sec {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".productimg {\r\n");
      out.write("\tmargin-left: 15%;\r\n");
      out.write("\tmargin-right: 30%;\r\n");
      out.write("\tmargin-bottom: 10%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#detail {\r\n");
      out.write("\t\r\n");
      out.write("\tmargin-left: 30%;\r\n");
      out.write("\tmargin-right: 30%;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#buy').click(function(){\r\n");
      out.write("\t\tvar text = $('#text').val();\r\n");
      out.write("\t\tlocation.href = \"/Cacao/Order?cmd=main-page&id=");
      out.print(id);
      out.write("&cnt=\"+document.getElementById(\"text\").value+\"&cart=1\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#plus').click(function(){\r\n");
      out.write("\t\t$('#text').val(parseInt($('#text').val())+1);\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#minus').click(function(){\r\n");
      out.write("\t\t$('#text').val($('#text').val()-1);\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cart').click(function(){\r\n");
      out.write("\t\tvar text = $('#text').val();\r\n");
      out.write("\t\tlocation.href=\"/Cacao/view/main/cartView.jsp?cnt=\"+text+\"&name=");
      out.print(name);
      out.write("&price=");
      out.print(price);
      out.write("&id=");
      out.print(id);
      out.write("\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#choose').click(function(){\r\n");
      out.write("\t\tvar text = $('#text').val();\r\n");
      out.write("\t\tlocation.href=\"/Cacao/view/main/cartView.jsp?cnt=\"+text+\"&name=");
      out.print(name);
      out.write("&price=");
      out.print(price);
      out.write("&id=");
      out.print(id);
      out.write("\";\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<section id=\"home\">\r\n");
      out.write("\t\t<div id=\"home-carousel\" class=\"carousel slide\" data-interval=\"false\">\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<li data-target=\"#home-carousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t");
for(int i=1;i<cnt;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li data-target=\"#home-carousel\" data-slide-to=\"");
      out.print(i);
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<!--/.carousel-indicators-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"item active\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url('/Cacao/img/product/all/");
      out.print(id);
      out.write("00.jpg');\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
for(int i=1;i<cnt;i++){ 
				if(i>10){
					imgstr = String.valueOf(i);
				}else{
					imgstr = "0"+String.valueOf(i);
				}
				
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url('/Cacao/img/product/all/");
      out.print(id);
      out.print(imgstr);
      out.write(".jpg');\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.carousel-inner-->\r\n");
      out.write("\t\t\t<nav id=\"nav-arrows\"\r\n");
      out.write("\t\t\t\tclass=\"nav-arrows hidden-xs hidden-sm visible-md visible-lg\">\r\n");
      out.write("\t\t\t\t<a class=\"sl-prev hidden-xs\" href=\"#home-carousel\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-angle-left fa-3x\"></i>\r\n");
      out.write("\t\t\t\t</a> <a class=\"sl-next\" href=\"#home-carousel\" data-slide=\"next\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-angle-right fa-3x\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- \t여기서부터 상품 그림 설명 -->\r\n");
      out.write("\t<section id=\"sec\" style=\"height: ");
      out.print(cnt*700);
      out.write("px;\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
for(int i=0;i<cnt;i++){ 
		
				if(i>10){
					imgstr = String.valueOf(i);
				}else{
					imgstr = "0"+String.valueOf(i);
				}
				
				
				
      out.write(" \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"productimg\">\r\n");
      out.write("\t\t\t\t<img src=\"/Cacao/img/product/all/");
      out.print(id);
      out.print(imgstr);
      out.write(".jpg\" width=1000\r\n");
      out.write("\t\t\t\t\theight=500 />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"detail\" style=\"height: 200px; margin-bottom:10%\">상품설명<br/>");
      out.print(detail );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/include/buy.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/view/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
